### ISSUE TITLE
Readme for paths?

### ISSUE THREAD

**Issue by TopperBG** [Cr4zyy/Radarr-Transmission-Fixer#1]
It isn't clear in row:
`DLDIR=" " #Name of the folder sonarr downloads all torrents into, can be customised with 'Category' option in download client options`
DLDIR is the realative or absolute path, per Radarr or per Transmission ?
- as per docker container mounted full path dir: `DLDIR="/data/downloads/Sonarr"`
- as custom category in Radarr just `DLDIR="Sonarr"` 
described here:
> Adding a category specific to Radarr avoids conflicts with unrelated non-Radarr downloads. Using a category is optional, but strongly recommended. Creates a [category] subdirectory in the output directory.

**Comment by Cr4zyy** [comment]
As per the category you set in sonarr/radarr `DLDIR="sonarr"`

Been a while since I looked at it but its pretty much a check to see if its got to move a whole folder after download or not so it compares against the custom path set in the your arr app.
